### ISSUE TITLE
Cannot make a build on Android

### ISSUE THREAD

**Issue by mrpacogp** [aniketrajnish/Unity-Collider-Optimizer#3]
<img width="815" alt="Captura de pantalla 2023-10-03 a las 19 23 39" src="https://github.com/aniketrajnish/Unity-Collider-Optimizer/assets/3923103/fb46cbad-7752-47ff-b984-ef8a0225ec25">
I just testing but cannot make a build

**Comment by aniketrajnish** [comment]
I'll fix it

**Comment by aniketrajnish** [comment]
Fixed!

**Comment by aniketrajnish** [comment]
Fixed!

**Comment by mrpacogp** [comment]
Thanks for support ;)
